spring:
  application:
    name: itau-service
  kafka:
    consumer:
      bootstrap-servers: pix-kafka:9092
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: pix-kafka:9092
      client-id: "myId"
      properties:
        spring.json.trusted.packages: "*"
#  datasource:
#    url: jdbc:postgresql://act-movies-db:5432/postgres
#    username: postgres
#    password: postgres
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://pix-eureka:8761/eureka/
  instance:
    hostname: pix-itau
