spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: itau-service
          uri: lb://ITAU-SERVICE
          predicates:
            - Path=/api/itau/**
        - id: bacen-service
          uri: lb://BACEN-SERVICE
          predicates:
            - Path=/api/bacen/**

server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://pix-eureka:8761/eureka/
  instance:
    hostname: pix-gateway
